name: Run RSpec tests

on: [push]

env:
  RAILS_ENV: test
  DB_HOST: 127.0.0.1
  DB_NAME: blog_test
  DB_USER: app
  DB_PASS: '1234'
  # POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: app
          POSTGRES_PASSWORD: '1234'
        ports:
        - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.2
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: "Install Node.js"
        uses: actions/setup-node@v1
      - name: "Compile Assets"
        shell: bash
        run: |
            yarn build:css

      - name: Run tests
        run: |
          bundle exec rails db:setup
          bundle exec rspec
